name: esmail_clinic_app
description: Esmail Clinic Arabic booking app (RTL + embedded Arabic font)
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/NotoNaskhArabic-Regular.ttf
        - asset: assets/NotoNaskhArabic-Bold.ttf
          weight: 700
